import type { Metadata } from "next";
import "./globals.css";
import { NotificationProvider } from "@/context/NotificationContext";
import { ChatProvider } from "@/context/ChatContext";

export const metadata: Metadata = {
   title: "Hav Imobiliária",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="pt-br">
         <body className={`antialiased`}>
            <NotificationProvider>
               {children}
            </NotificationProvider>
         </body>
      </html>
   );
}
